name: ci-expense-authorization-portal-ui

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "expense-authorization/src/UI/**"
      - ".github/workflows/ci-expense-authorization-portal-ui.yml"

env:
  IMAGE_NAME: expense-authorization-ui

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        working-directory: expense-authorization/src/UI
        run: docker build . --file Dockerfile --tag $IMAGE_NAME
